apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-1

managedNodeGroups:
  - name: spot
    # instanceType: m5.large   # it is having a bit more cost
    instanceType: m5.large
    desiredCapacity: 3
    spot: true